# Generated by Django 4.2.9 on 2024-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uploadedphotos_brightness_uploadedphotos_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='brightness',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='contrast',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='rotation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
