# Generated by Django 4.2.9 on 2024-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_albums_brightness_albums_contrast_albums_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_brightness',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_contrast',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
