# Generated by Django 4.2.9 on 2024-03-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_albums_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='country',
        ),
    ]
