# Generated by Django 4.2.9 on 2024-03-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphotos',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.regions'),
        ),
        migrations.AddField(
            model_name='uploadedvideos',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.regions'),
        ),
    ]
