# Generated by Django 4.2.9 on 2024-03-24 10:35

import base.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_uploadedphotos_region_uploadedvideos_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphotos',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(default='ava1.jpg', null=True, upload_to=base.models.get_photo_upload_path),
        ),
    ]
