# Generated by Django 4.2.9 on 2024-03-24 10:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_uploadedphotos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphotos',
            name='photo',
            field=models.ImageField(default='ava1.jpg', null=True, upload_to=base.models.get_photo_upload_path),
        ),
    ]
